parameters:
  - name: 'vmImage'
    default: 'ubuntu-18.04'
    type: string

jobs:
  - job: Build
    displayName: "Build"
    pool:
      vmImage: ${{ parameters.vmImage }}
    workspace:
      clean: all
    steps:
    - bash: |
        git clone https://github.com/tfutils/tfenv.git ~/.tfenv
        export PATH="$HOME/.tfenv/bin:$PATH"
        tfenv install
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      displayName: 'Sets terraform version to the specified on .terraform-version file'
    - bash: |
        export PATH="$HOME/.tfenv/bin:$PATH"
        terraform init
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      displayName: 'Terraform Init'
      env:
        ARM_ACCESS_KEY: $(ARM_ACCESS_KEY)
    - bash: |
        export PATH="$HOME/.tfenv/bin:$PATH"
        terraform validate
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      displayName: 'Terraform Validate'
    - bash: |
        export PATH="$HOME/.tfenv/bin:$PATH"
        terraform plan
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      displayName: 'Terraform Plan'
    - publish: '$(System.DefaultWorkingDirectory)'
      artifact: build